---
- name: Configure backend locally
  hosts: localhost
  connection: local
  gather_facts: yes
  become: yes

  vars:
    app_dir: /srv/todolistapp
    app_src_dir: "{{ app_dir }}/src"

    repo_url: "https://github.com/jkozienski/todolist-cloud-project.git"
    repo_version: "main"

    aws_region: "{{ aws_region | default('us-east-1') }}"
    app_env: "{{ app_env | default('dev') }}"
    ssm_prefix: "/todolist/{{ app_env }}/api"

  roles:
    - backend
