---
- name: Configure backend locally
  hosts: localhost
  connection: local
  gather_facts: yes
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3
    app_dir: /srv/todolistapp
    app_src_dir: "{{ app_dir }}/src"

    repo_url: "https://github.com/jkozienski/todolist-cloud-project.git"
    repo_version: "main"

    aws_region: "{{ aws_region }}"
    ssm_prefix: "{{ ssm_prefix }}"


  roles:
    - backend
 