---
- name: Configure backend locally
  hosts: localhost
  connection: local
  gather_facts: yes
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3
    app_dir: /srv/todolistapp
    app_src_dir: "{{ app_dir }}/src"

  
    repo_version: "main"
    source_repo_url: "{{ source_repo_url }}"
    aws_region: "{{ aws_region }}"
    ssm_prefix: "{{ ssm_prefix }}"


  roles:
    - backend
 