---
- name: Configure frontend on web instances
  hosts: localhost
  connection: local
  gather_facts: yes
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3
    source_repo_url: "{{ source_repo_url }}"
    frontend_dir: /var/www/{{ app_name }}
    repo_checkout_dir: /opt/todolist-app

  roles:
    - frontend
